/* eslint-disable @next/next/no-page-custom-font */
import { NextPage } from 'next'
import Head from 'next/head'
import Card from 'src/components/Card'
import { Button } from 'src/components/design/button'
import ModalNota from 'src/components/ModalNotas'
import { Container, ContainerIndex } from 'src/components/design/container'
import Header from 'src/components/Header'
import Menu from 'src/components/Menu'
import * as S from 'src/style/page/anotacoes.style'
import { useState, MouseEvent } from 'react'
import useGlobalColor from 'src/hooks/globalColor'
import { useSelector } from 'react-redux'
import { RootState } from 'src/store'

const Anotacoes: NextPage = () => {
  const [handleStateModal, setHandleStateModal] = useState(false)
  const globalColor = useGlobalColor()

  const totalNotes: Array<object> = useSelector(
    (state: RootState) => state.globalNotes
  )

  const handleModal = (e: boolean) => {
    setHandleStateModal(e)
  }

  console.log(totalNotes)
  return (
    <Container>
      <Head>
        <title>Boost yourself</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link
          href="https://fonts.googleapis.com/css2?family=Rye&display=swap"
          rel="stylesheet"
        />
        <link
          href="https://fonts.googleapis.com/css2?family=Roboto:wght@100&display=swap"
          rel="stylesheet"
        />
      </Head>
      <ContainerIndex>
        <Header />
        <S.ContainerAnotacoes>
          <Button
            type="button"
            color={globalColor}
            onClick={(e: MouseEvent) => handleModal(true)}
          >
            Criar anotações
          </Button>
          <section>
            {totalNotes.map((item: any) => (
              <Card
                key={item.id}
                title={item.title}
                subtitle={item.subtitle}
                textarea={item.textarea}
                color={item.color}
              />
            ))}
          </section>
          {handleStateModal ? (
            <S.ModalDiv>
              <ModalNota modal={handleModal} />
            </S.ModalDiv>
          ) : (
            <></>
          )}
        </S.ContainerAnotacoes>
      </ContainerIndex>
      <Menu />
    </Container>
  )
}

export default Anotacoes
