/* eslint-disable @next/next/no-page-custom-font */
import { NextPage } from 'next'
import Head from 'next/head'
import Card from 'src/components/Card'
import { Button } from 'src/components/design/button'
import ModalNota from 'src/components/ModalNotas'
import { Container, ContainerIndex } from 'src/components/design/container'
import Header from 'src/components/Header'
import Menu from 'src/components/Menu'
import { lightBlue } from 'src/style/colors'
import * as S from 'src/style/page/anotacoes.style'
import { useState, MouseEvent, KeyboardEvent } from 'react'

const Anotacoes: NextPage = () => {
  const [handleStateModal, setHandleStateModal] = useState(false)

  const handleModal = (e: boolean) => {
    setHandleStateModal(e)
  }

  return (
    <Container>
      <Head>
        <title>Boost yourself</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link
          href="https://fonts.googleapis.com/css2?family=Rye&display=swap"
          rel="stylesheet"
        />
        <link
          href="https://fonts.googleapis.com/css2?family=Roboto:wght@100&display=swap"
          rel="stylesheet"
        />
      </Head>
      <ContainerIndex>
        <Header />
        <S.ContainerAnotacoes>
          <Button
            type="button"
            color={lightBlue}
            onClick={(e: MouseEvent) => handleModal(true)}
          >
            Criar anotações
          </Button>
          <section>
            <Card />
            <Card />
            <Card />
          </section>
          {handleStateModal ? (
            <S.ModalDiv>
              <ModalNota modal={handleModal} />
            </S.ModalDiv>
          ) : (
            <></>
          )}
        </S.ContainerAnotacoes>
      </ContainerIndex>
      <Menu />
    </Container>
  )
}

export default Anotacoes
