/* eslint-disable @next/next/no-page-custom-font */
import type { NextPage } from 'next'
import Head from 'next/head'
import Card from '../components/Card'
import Header from '../components/Header'
import Menu from '../components/Menu'
import ToDoItem from '../components/ToDoItem'
import { GridCards, GridToDo } from 'src/style/page/index.style'
import { Container, ContainerIndex } from '../components/design/container'
import * as S from 'src/style/page/index.style'
import { useSelector } from 'react-redux'
import { RootState } from 'src/store'

const Home: NextPage = () => {
  const totalTasks: Array<object> = useSelector(
    (state: RootState) => state.globalTasks
  )
  console.log(totalTasks)
  return (
    <Container>
      <Head>
        <title>Boost yourself</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link
          href="https://fonts.googleapis.com/css2?family=Rye&display=swap"
          rel="stylesheet"
        />
        <link
          href="https://fonts.googleapis.com/css2?family=Roboto:wght@100&display=swap"
          rel="stylesheet"
        />
      </Head>

      <ContainerIndex>
        <Header />
        <S.ContainerContent>
          <GridCards></GridCards>

          <GridToDo>
            {totalTasks.map((item: any) => (
              <ToDoItem text={item.textInput} key={item.id} />
            ))}
          </GridToDo>
        </S.ContainerContent>
      </ContainerIndex>
      <Menu />
    </Container>
  )
}

export default Home
