/* eslint-disable @next/next/no-page-custom-font */
import { Container, ContainerIndex } from 'src/components/design/container'
import * as S from 'src/style/page/tasks.style'
import Head from 'next/head'
import Header from 'src/components/Header'
import Menu from 'src/components/Menu'

const Tasks: React.FC = () => {
  return (
    <Container>
      <Head>
        <title>Boost yourself</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link
          href="https://fonts.googleapis.com/css2?family=Rye&display=swap"
          rel="stylesheet"
        />
        <link
          href="https://fonts.googleapis.com/css2?family=Roboto:wght@100&display=swap"
          rel="stylesheet"
        />
      </Head>
      <ContainerIndex>
        <Header />
        <S.ContainerTasks>
          <h1>Hello world</h1>
          <h2>aushuash</h2>
        </S.ContainerTasks>
      </ContainerIndex>
      <Menu />
    </Container>
  )
}
export default Tasks
